ShortestRouteOptimizerMVCApp/Models/NodeValidator.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ShortestRouteOptimizerMVCApp.Models
{
    [AttributeUsage(AttributeTargets.Property |
  AttributeTargets.Field, AllowMultiple = false)]
    public sealed class NodeValidator : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            bool isValid = false;
            char node;
            if (value == null)
            {
                return isValid;
            }

            isValid = char.TryParse(value.ToString().ToUpper(), out node);

            if (isValid)
            {
                isValid = node >= char.Parse("A") && node <= char.Parse("I");
            }

            return isValid;
        }
    }
}

ShortestRouteOptimizerMVCApp/Models/ShortestPathData.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ShortestRouteOptimizerMVCApp.Models
{
    public class ShortestPathData
    {
        [DisplayName("Start Node")]
        [Required]
        [NodeValidator(ErrorMessage = "Entered Node is not a valid node")]
        public string StartNode { get; set; }

        [DisplayName("Finish Node")]
        [Required]
        [NodeValidator(ErrorMessage = "Entered Node is not a valid node")]
        public string FinishNode { get; set; }

        public int ShortestDistance { get; set; }

        public List<string> NodeNames { get; set; }

        public string[] InitialNodeNames { get; set; }
    }
}

ShortestRouteOptimizerMVCApp/Controllers/ShortestPathController.cs
using ShortestPathCalculatorApplication;
using ShortestPathCalculatorApplication.IServices;
using ShortestRouteOptimizerMVCApp.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ShortestRouteOptimizerMVCApp.Controllers
{
    public class ShortestPathController : Controller
    {
        private readonly IShortestPathCalculator _shortestPathCalculator;
        private readonly INodeDataService _nodeDataService;


        public ShortestPathController(
            IShortestPathCalculator shortestPathCalculator,
            INodeDataService nodeDataService)
        {
            _shortestPathCalculator = shortestPathCalculator;
            _nodeDataService = nodeDataService;

        }

        // GET: ShortestPath
        public ActionResult Calculate()
        {
            var shortestPathData = (ShortestPathData)TempData["shortest_path"];
            if (shortestPathData == null)
            {
                return RedirectToAction("Index");
            }
            return View(shortestPathData);
        }

        // GET
        public ActionResult Index()
        {
            string[] initialNodeNames = _nodeDataService.ProvideInitialNodes();
            ShortestPathData shortestPathData = new ShortestPathData();
            shortestPathData.InitialNodeNames = initialNodeNames;

            return View(shortestPathData);
        }

        // POST
        [HttpPost]
        public ActionResult Index(ShortestPathData shortestPathData)
        {
            if (shortestPathData?.StartNode != null &&
                shortestPathData?.FinishNode != null &&
                shortestPathData.StartNode.ToUpper().Equals(shortestPathData.FinishNode.ToUpper()))
            {
                ModelState.AddModelError("FinishNode", "Finish node should be different from start node");
            }

            if (ModelState.IsValid)
            {
                ShortestPathDto shortestPathDto = _shortestPathCalculator.CalculateShortestPath(shortestPathData.StartNode, shortestPathData.FinishNode);

                ShortestPathData shortestPath = new ShortestPathData()
                {
                    StartNode = shortestPathData.StartNode,
                    FinishNode = shortestPathData.FinishNode,
                    ShortestDistance = shortestPathDto.Distance,
                    NodeNames = shortestPathDto.NodeNames.Select(n => n).ToList(),
                };
                TempData["shortest_path"] = shortestPath;
                return RedirectToAction("Calculate");
            }

            string[] initialNodeNames = _nodeDataService.ProvideInitialNodes();
            shortestPathData.InitialNodeNames = initialNodeNames;
            return View(shortestPathData);
        }
    }
}

ShortestRouteOptimizerMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Shortest Route Optimizer", "Index", "ShortestPath", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row pt-4">
                <div class="col-6">
                    <p>
                        &copy; @DateTime.Now.Year - Shortest Path Optimizer Application.
                    </p>
                </div>
                <div class="col-6 text-end">
                    Implemented by Supun Priyamantha
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShortestRouteOptimizerMVCApp/Views/ShortestPath/Calculate.cshtml
@model ShortestRouteOptimizerMVCApp.Models.ShortestPathData
@{
    ViewData["Title"] = "Index";
}

<h2>Shortest Path Data</h2>
<div class="border p-3 mt-4">
    <div class="mb-3">
        Start Node :
        <div class="col-md-10">
            @Model.StartNode.ToUpper()
        </div>
    </div>

    <div class="mb-3">
        Finish Node :
        <div class="col-md-10">
            @Model.FinishNode.ToUpper()
        </div>
    </div>
    <div class="mb-3">
        Shortest Distance :
        <div class="col-md-10">
            @Model.ShortestDistance
        </div>
    </div>
    <div class="mb-3">
        Optimal Node Sequance :
        <div class="col-md-10">
            <table>
                <tr>
                    @foreach (var obj in @Model.NodeNames)
                    {
                        <td>@obj</td>
                        <td>&nbsp; &nbsp; </td>
                    }
                </tr>
            </table>
        </div>
    </div>
    <a href="Index" style="width:250px">
        Back To Shortest Path Calculator
    </a>
</div>

ShortestRouteOptimizerMVCApp/Views/ShortestPath/Index.cshtml
@model ShortestRouteOptimizerMVCApp.Models.ShortestPathData

@{
    ViewBag.Title = "ShortestPath";
}

<h2>Shortest Path Calculator</h2>

@using (Html.BeginForm("Index", "ShortestPath", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="border p-3 mt-4">
        <div class="mb-3">
            <label><b>You have nodes from A - I. You can select a start node and a finish node to calculate the shortest distance and the optimal path.</b></label>
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.StartNode, "Start Node :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StartNode,
                new SelectList(Model.InitialNodeNames.Select(n => n).ToList()),
                "Select Node")
                @Html.ValidationMessageFor(model => model.StartNode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.FinishNode, "Finish Node :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FinishNode,
                new SelectList(Model.InitialNodeNames.Select(n => n).ToList()),
                "Select Node")
                @Html.ValidationMessageFor(model => model.FinishNode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Calculate" class="btn btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")